### ISSUE TITLE
Hi, can you add my name to your LICENSE since this project uses a lot of code from mine?

### ISSUE THREAD

**Issue by nickjj** [zakariaf/rails-base-app#28]
Thanks for linking to the original project at https://github.com/nickjj/docker-rails-example in your readme file.

Since a lot of code from that project is being used in your project, can you add my name to your license file to adhere to the MIT license itself?

You can drop this in under your name:

```
Copyright (c) 2020 Nick Janetakis <nick.janetakis@gmail.com>
```

**Comment by zakariaf** [comment]
I apologize for the oversight. I'll make sure to address this promptly. I would greatly value your expertise in the field of Dockerizing projects, as you are among the most experienced individuals in this area. Your contributions to this project would be greatly appreciated and I am eager to work with you to make it a success.

**Comment by nickjj** [comment]
It's all good, thanks!
